# https://github.com/consiglionazionaledellericerche/cool-jconon/blob/master/cool-jconon-backend/src/main/resources/config/application.yaml
user:
  admin:
    password: password
oil:
  url: http://10.12.12.20:9081/rest
  username: admin
  password: password
server:
  servlet:
    context-path: /
repository:
  base:
    url: http://10.12.12.20:9080/alfresco/
spid:
  enable: true  
  issuer:
    entity_id: https://www.aspbassaromagna.it
  destination: https://bandi.aspbassaromagna.it/spid/send-response
siper:
  static:
    sedi: true
rrd:
  path: remote-shared,remote-single-model
ipa:
  url:
    base: https://www.indicepa.gov.it/public-services/opendata-read-service.php
    amministrazioni: ${ipa.url.base}?dstype=FS&filename=amministrazioni.txt
attiva:
  mail:
    solleciti: false
  protocol:
    application: true
multipart:
  resolver:
    max:
      upload:
        size: 10485760
    default:
      upload:
        size: 5242880
mail:
  host: smtps.pec.aruba.it
  port: 587
  username: user
  password: password
  smtp:
    host: ${mail.host}
    user: ${mail.username}
    password: ${mail.password}
    auth: true
    starttls:
      enable: true
  encoding: UTF-8
  from:
    default: concorsiaspbassaromagna@pec.it
  admin: staffdirezione@aspbassaromagna.it
  to:
    error:
      message: assistenza@electroninformatica.it
  helpdesk: assistenza@electroninformatica.it
  error:
    enabled: true
  create:
    user:
      bcc:
        enabled: true

